name: telomore
channels:
  - conda-forge
  - bioconda
dependencies:
  - bioconda::last
  - bowtie2
  - emboss
  - lamassemble
  - mafft
  - minimap2=>2.25
  - pip
  - python=3.14
  - samtools
  - pip:
      - biopython
      - pysam
